---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: "Swift object server configuration"
  openstack.config_template.config_template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ swift_system_user_name }}"
    group: "{{ swift_system_group_name }}"
    mode: "0644"
    config_overrides: "{{ item.config_overrides }}"
    config_type: "{{ item.config_type }}"
  with_items:
    - src: "object-server.conf.j2"
      dest: "/etc/swift/object-server/object-server.conf"
      config_overrides: "{{ swift_object_server_conf_overrides }}"
      config_type: "ini"
    - src: "object-expirer.conf.j2"
      dest: "/etc/swift/object-server/object-expirer.conf"
      config_overrides: "{{ swift_object_expirer_conf_overrides }}"
      config_type: "ini"
  notify: Restart swift services

# We only create the dedicated replicator configuration when using a dedicated replication_network
- name: "Swift object server replicator configuration"
  openstack.config_template.config_template:
    src: "object-server-replicator.conf.j2"
    dest: "/etc/swift/object-server/object-server-replicator.conf"
    owner: "{{ swift_system_user_name }}"
    group: "{{ swift_system_group_name }}"
    mode: "0644"
    config_overrides: "{{ swift_object_server_replicator_conf_overrides }}"
    config_type: "ini"
  when: swift_dedicated_replication
  notify: Restart swift services

# Remove the dedicated replicator configuration when no dedicated replication network in use
- name: "Remove dedicated replicator configuration"
  ansible.builtin.file:
    state: absent
    path: "/etc/swift/object-server/object-server-replicator.conf"
  when: not swift_dedicated_replication | bool

- name: Deploy drive-audit configuration file
  openstack.config_template.config_template:
    src: drive-audit.conf.j2
    dest: /etc/swift/drive-audit.conf
    owner: "{{ swift_system_user_name }}"
    group: "{{ swift_system_group_name }}"
    mode: "0644"
    config_overrides: "{{ swift_drive_audit_conf_overrides }}"
    config_type: "ini"

- name: Create drive-audit systemd timer
  ansible.builtin.include_role:
    name: systemd_service
  vars:
    systemd_service_restart_changed: false
    systemd_user_name: "root"
    systemd_group_name: "root"
    systemd_tempd_prefix: openstack
    systemd_slice_name: "{{ swift_system_slice_name }}"
    systemd_lock_dir: "{{ swift_lock_dir }}"
    systemd_service_restart: on-abnormal
    systemd_services:
      - service_name: "swift-drive-audit"
        execstarts:
          - "{{ swift_bin }}/swift-drive-audit /etc/swift/drive-audit.conf"
        environment:
          UMASK: "0640"
          UMASK_DIR: "0750"
        program_sandboxing:
          RuntimeDirectory: "swift-drive-audit"
        enabled: true
        timer:
          state: 'started'
          enabled: true
          options:
            OnCalendar: "*:0/15"
            Persistent: true
            Unit: "swift-drive-audit.service"
